### ISSUE TITLE
A way to set FAB, to scroll it up/down as Snackbar is shown?

### ISSUE THREAD

**Issue by conzorz** [matecode/Snacky#1]
As in Google apps

**Comment by matecode** [comment]
I think this has nothing to do with the Snackbar, but with the use of CoordinatorLayout and android.support.design.widget.FloatingActionButton. Then use the Coordinatorlayout as view in .setView() .

But I will investigate this... and see if this is a usecase for Snacky. Does not feel like it is...

**Comment by matecode** [comment]
In the new version of this library you find the example on how to use a SnackBar with FAB and Coordinatorlayout. Have fun
