### ISSUE TITLE
Action text size 

### ISSUE THREAD

**Issue by arashmidos** [matecode/Snacky#2]
Hi,

I changed the text size of snacky and works great, but action text size wont change. 

![snacky](https://cloud.githubusercontent.com/assets/11665792/23627948/ee8d5d32-02c7-11e7-9d9b-40e01bc82068.JPG)

As you can see in attached screenshot, action button on the right side, is smaller than message text.

**Comment by matecode** [comment]
Thanks for your feedback. Just released version 1.0.2 where you can set the TextSize also for the ActionButton. As little extra you can also set a TypeFace Style.
