### ISSUE TITLE
Failed to resolve Snacky

### ISSUE THREAD

**Issue by congdanh1608** [matecode/Snacky#4]
com.github.matecode:Snacky:1.0.2

Are you sure Snacky still on Maven, i checked it on the central repository. It not found.
https://search.maven.org/#search%7Cga%7C1%7Csnacky

That same in dependencies of android studio .

**Comment by GrenderG** [comment]
Mate, take a loot [here](https://github.com/matecode/Snacky#installation). You need to add the `jitpack` url as this library is published using that service.

**Comment by matecode** [comment]
@congdanh1608  Sorry for the late answer. Follow the [install instructions](https://github.com/matecode/Snacky#installation), you have to add jitpack.
