### ISSUE TITLE
Is it possible to queue the snack messages

### ISSUE THREAD

**Issue by erikswed** [matecode/Snacky#5]
hi I like your lib. Is the snack messages queued at any time so user don't miss a message?
If not, is that hard to do what would your suggestion be?

**Comment by matecode** [comment]
Snacky is not a snackbar implementation library, it is just a builder wrapper for the support-lib snackbar implementation. So if you use Snacky, you get a snackbar object as you would if you use Snackbar.[make](https://developer.android.com/reference/android/support/design/widget/Snackbar.html#make(android.view.View,%20java.lang.CharSequence,%20int)) from the support-lib.

The snackbar object is a [BaseTransientBottomBar](https://developer.android.com/reference/android/support/design/widget/BaseTransientBottomBar.html) where you can find more info about queuing or showing the BaseTransientBottomBar.
